### ISSUE TITLE
Angular 5.x compatibility issue

### ISSUE THREAD

**Issue by Shinzah** [Gbuomprisco/ngx-chips#593]
**I'm submitting a ...** 
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: 
Angular 5.0.0 remove ngOutletContext in favor of ngTemplateOutletContext

common: NgTemplateOutlet#ngOutletContext has been removed as it was deprecated since v4. Use NgTemplateOutlet#ngTemplateOutletContext instead.

**Current behavior**
On build, the build faild because of a renamed attribute on ng-template component :

```
ERROR in Error at node_modules/ngx-chips/dist/modules/components/tag/tag.template.html(13,13):  ("
        <!-- CUSTOM TEMPLATE -->
        <ng-template
            [ERROR ->][ngOutletContext]="{ item: model, index: index }"
            [ngTemplateOutlet]="template">
        ")
Error at node_modules/ngx-chips/dist/modules/components/tag/tag.template.html(12,9):  ("div *ngSwitchCase="true" [attr.contenteditable]="editing">
        <!-- CUSTOM TEMPLATE -->
        [ERROR ->]<ng-template
            [ngOutletContext]="{ item: model, index: index }"
            [ngTemplateOut")
```

**Minimal reproduction of the problem with instructions (if applicable)**
Just compile with angular 5.0.0

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
5.0.0

**ngx-chips version:**
latest

**Browser:** 
all

**Comment by MonasteryJohn** [comment]
Looks like the issue has already been corrected in the source, just need a new release with that fix.

**Comment by Gbuomprisco** [comment]
Hi, ngx-chips 1.5.4 has been released. Reopen if still an issue :)

**Comment by maxkorz** [comment]
@Gbuomprisco There's still an issue with peerDependencies:
Instead of
```json
  "peerDependencies": {
    "@angular/common": "^4.2.0",
    "@angular/core": "^4.2.0",
    "@angular/forms": "^4.2.0",
    "@angular/animations": "^4.2.0",
    "rxjs": "^5.0.1"
  },
```
It should be
```json
  "peerDependencies": {
    "@angular/common": ">=4.2.0",
    "@angular/core": ">=4.2.0",
    "@angular/forms": ">=4.2.0",
    "@angular/animations": ">=4.2.0",
    "rxjs": "^5.0.1"
  },
```

to not throw a warning on angular 5
