### ISSUE TITLE
validator is not working on edit tags

### ISSUE THREAD

**Issue by na-le** [Gbuomprisco/ngx-chips#663]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

validator is not working while editing tags

**Expected behavior**

validator should work when user is editing a tag

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
this should be fixed with v 1.7.0

**Comment by alinakuchai** [comment]
Hi. Is this problem still unresolved?

**Comment by jsalvata** [comment]
This problem is still (again?) unresolved in 1.9.2.

I've tracked it down to the fact that `TagInputComponent.updateEditedTag`, unlike `TagInputComponent.appendTag` and `TagInputComponent.removeItem`, never sets `this.items` and so `this._onChangeCallback` is never called.

I've worked around the issue by listening to `onTagEdited` and setting `items` appropriately:

```
      <tag-input ...
          #tagInput (onTagEdited)="change($event, tagInput)" ...>
```

```
  changeEmail(event: { value: any }, input: { items: { value: any }[] }) {
    input.items= _.map(input.items, (item) => item.value == event.value ? event : item);
    return event;
  }
```
