### ISSUE TITLE
onTextChange is not passing text back to the component

### ISSUE THREAD

**Issue by ceeliro** [Gbuomprisco/ngx-chips#732]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

```

**Current behavior**
onTextChange($event) not passing back text entered

**Expected behavior**
when implementing this function I expect to receive the value entered in the UI

**Minimal reproduction of the problem with instructions (if applicable)**
You can see the behaviour in the demo page. Console always shows 'text changed: value is '

**What do you use to build your app?. Please specify the version**
Angular CLI 1.7.4

**Angular version:** 
Angular 5

**ngx-chips version:**
Can reproduce with latest version see online demo

**Browser:**

**Comment by Gbuomprisco** [comment]
This should be fixed in v 1.8.2

**Comment by iamwhitebox** [comment]
This is still not working for me in v1.8.2, cannot figure out why.
