### ISSUE TITLE
typeahead results Angular 8 window doesn't show in IE 11 or Edge, display:none is never updated

### ISSUE THREAD

**Issue by daddyschmack** [Gbuomprisco/ngx-chips#885]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

when I click in the field, the typeahead window doesn't show

**Expected behavior**

the typeahead window should be visible

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular-cli

**Angular version:** 

Angular 8.0

**ngx-chips version:**

2.0.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11,
Edge
example site won't load in ie11, either:
https://angular-mfppay.stackblitz.io/

**Comment by dmitrynop** [comment]
I think it's the same issue as it was in Safari.
I fixed it in the dependency of this package earlier, but it waits for merging and bumping of versions.
https://github.com/Gbuomprisco/ng2-material-dropdown/pull/50
https://github.com/Gbuomprisco/ngx-chips/issues/877

**Comment by daddyschmack** [comment]
Unless I missed something, It didnt solve the same way.   We had to
override the style by setting a case property with atag with I display flex
instead of display none, and then it works just fine

**Comment by azuxx** [comment]
> Unless I missed something, It didnt solve the same way. We had to override the style by setting a case property with atag with I display flex instead of display none, and then it works just fine

Hi, could you show me how did you make it work on Safari please? 

Here's my template (working well with Chrome)

`<tag-input class="hashtags"
                     [(ngModel)]="object[field.key]"
                     [onlyFromAutocomplete]="true"
                     [displayBy]="field.selectedItemDisplayBy"
                     [identifyBy]="field.selectedItemKey">
            <tag-input-dropdown [showDropdownIfEmpty]="false"
                                [displayBy]="field.selectedItemDisplayBy"
                                [identifyBy]="field.selectedItemKey"
                                [autocompleteItems]="field.selectOptions">
            </tag-input-dropdown>
          </tag-input>`

Looking forward to hearing from you
